name: symjepa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - pytorch-lightning=2.2.5
  - torchtext=0.15.2
  - pip
  - pip:
    - transformers==4.10.2
    - pretty-midi==0.2.10
    - torchdata==0.6.1
    - wandb==0.19.7
    - python-dotenv==1.0.1
    - miditoolkit==1.0.1
