name: symjepa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchaudio
  - pytorch-cuda=11.7
  - pytorch-lightning=2.2.5
  - ray-tune=2.9.3
  - numpy=1.26.4
  - mkl=2023.1.0
  - pip
  - pip:
    - transformers==4.10.2
    - pretty-midi==0.2.10
    - torchdata==0.6.1
    - python-dotenv==1.0.1
    - miditoolkit==1.0.1
    - mlflow==2.17.2
    - umap-learn==0.5.7
    - PyYAML>=6.0
    - setuptools>=65.0.0,<70.0.0
    - pillow==11.3.0
