name: symjepa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.3.1
  - pytorch-lightning=2.2.5
  - torchtext=0.15.2
  - pip
  - pip:
    - transformers==4.10.2
    - pretty-midi==0.2.9 